source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

link_with 'DVATableViewDatasource', 'Tests'

target 'DVATableViewDatasource', :exclusive => true do
    pod 'MagicalRecord', :inhibit_warnings => true
  pod "DVATableViewDatasource", :path => "../"
end


target 'Tests', :exclusive => true do
    pod 'MagicalRecord', :inhibit_warnings => true
  pod "DVATableViewDatasource", :path => "../"
end
