source 'https://github.com/CocoaPods/Specs.git'


target 'DVATableViewDatasource', :exclusive => true do
  pod 'MagicalRecord', :inhibit_warnings => true
  pod "DVATableViewDatasource", :path => "../"
end


target 'Tests', :exclusive => true do
  pod 'MagicalRecord', :inhibit_warnings => true
  pod "DVATableViewDatasource", :path => "../"
end
