source 'https://github.com/CocoaPods/Specs.git'

target 'DVATableViewDatasource', :exclusive => true do
  pod "DVATableViewDatasource", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DVATableViewDatasource", :path => "../"

  
end
